["26.1-fabric"]
fabric_api_version = "0.145.1+26.1"
minecraft_range_start = "26.1-alpha.1"
minecraft_range_start_publish = "26.1-snapshot-1"
minecraft_range_end = "latest"
minecraft_range_end_publish = "latest"

["1.21.9-fabric"]
fabric_api_version = "0.134.1+1.21.9"
minecraft_range_start = "1.21.9-alpha.25.31.a"
minecraft_range_start_publish = "25w31a"
minecraft_range_end = "1.21.11"
minecraft_range_end_publish = "1.21.11"

["1.21.9-neoforge"]
forgelike_version = "21.9.16-beta"
minecraft_range_start = "1.21.9-alpha.25.31.a"
minecraft_range_start_publish = "25w31a"
minecraft_range_end = "latest"
minecraft_range_end_publish = "latest"

["1.20.6-neoforge"]
forgelike_version = "20.6.139"
minecraft_range_start = "1.20.6"
minecraft_range_start_publish = "1.20.6"
minecraft_range_end = "1.21.8"
minecraft_range_end_publish = "1.21.8"

["1.19.3-forge"]
forgelike_version = "1.19.3-44.1.23"
minecraft_range_start = "1.19.3"
minecraft_range_start_publish = "1.19.3"
minecraft_range_end = "1.20.4"
minecraft_range_end_publish = "1.20.4"

["1.19.3-fabric"]
fabric_api_version = "0.76.1+1.19.3"
minecraft_range_start = "1.19.3-alpha.22.42.a"
minecraft_range_start_publish = "22w42a"
minecraft_range_end = "1.21.8"
minecraft_range_end_publish = "1.21.8"
